"""Instrument/format seam.

The first half is a **golden parity table**: the exact classifications the
hard-coded REF_L regexes produced before they were consolidated into
``aure.instruments``. It was generated by running the old
``config._detect_kind``, ``intake._extract_set_id``,
``refl1d_import._extract_set_id`` and ``refl1d_import._detect_state_kind``,
and it exists so that moving that logic cannot silently change what REF_L
files mean. Do not "fix" a row here without deciding that the behaviour
change is intended.
"""

import os

import pytest

from aure import instruments as I
from aure.config import ConfigError, _detect_kind
from aure.instruments import COMBINED, PARTIAL, UNKNOWN
from aure.instruments.registry import _ENV_OVERRIDE
from aure.refl1d_import import _detect_state_kind

# ---------------------------------------------------------------------------
# Golden parity: per-file classification
# ---------------------------------------------------------------------------

# (basename, group_key, refl1d_import state kind)
GOLDEN_FILES = [
    ("REFL_226642_combined_data_auto.txt", "226642", "combined"),
    ("REFL_226642_1_2001_partial.txt", "226642", "partials"),
    ("REFL_226642_3_226644_partial.txt", "226642", "partials"),
    ("REFL_230536_1_230536_partial.txt", "230536", "partials"),
    ("REFL_1_combined_data.txt", None, "combined"),  # near-miss: no _auto
    ("REFL_230539.txt", None, "combined"),  # bare
    ("random.dat", None, "combined"),
    ("sample.ort", None, "combined"),
    ("data_combined_data_auto.txt", None, "combined"),  # no REFL_ prefix
    ("x_1_2_partial.txt", None, "partials"),  # no REFL_ prefix
]


@pytest.mark.parametrize("name,expected_key,_kind", GOLDEN_FILES)
def test_group_key_matches_legacy_set_id(name, expected_key, _kind):
    assert I.group_key("/d/" + name) == expected_key


@pytest.mark.parametrize("name,_key,expected_kind", GOLDEN_FILES)
def test_refl1d_import_state_kind_unchanged(name, _key, expected_kind):
    assert _detect_state_kind(["/d/" + name]) == expected_kind


# ---------------------------------------------------------------------------
# Golden parity: state classification via config._detect_kind
# ---------------------------------------------------------------------------

GOLDEN_STATES = [
    (["REFL_226642_combined_data_auto.txt"], "combined"),
    (
        ["REFL_226642_1_2001_partial.txt", "REFL_226642_2_2002_partial.txt"],
        "partials",
    ),
    (["REFL_1_combined_data.txt"], "combined"),
    (["REFL_230539.txt"], "combined"),
    (["random.dat"], "combined"),
    (
        [
            "REFL_226642_combined_data_auto.txt",
            "REFL_226660_combined_data_auto.txt",
        ],
        "combined",
    ),
]


@pytest.mark.parametrize("names,expected", GOLDEN_STATES)
def test_detect_kind_unchanged(names, expected):
    ds = [{"file": "/d/" + n} for n in names]
    assert _detect_kind("s", ds) == expected


def test_detect_kind_still_rejects_mixed_roles():
    ds = [
        {"file": "/d/REFL_226642_combined_data_auto.txt"},
        {"file": "/d/REFL_226642_1_2001_partial.txt"},
    ]
    with pytest.raises(ConfigError, match="cannot mix combined and partial"):
        _detect_kind("s", ds)


def test_detect_kind_still_rejects_mixed_set_ids():
    ds = [
        {"file": "/d/REFL_226642_1_2001_partial.txt"},
        {"file": "/d/REFL_226660_1_2001_partial.txt"},
    ]
    with pytest.raises(ConfigError, match="set_id"):
        _detect_kind("s", ds)


def test_partials_without_a_set_id_are_still_tolerated():
    """``x_1_2_partial.txt`` has a role but no group key; that combination
    passed the consistency check before and must keep passing."""
    ds = [{"file": "/d/x_1_2_partial.txt"}, {"file": "/d/y_3_4_partial.txt"}]
    assert _detect_kind("s", ds) == "partials"


# ---------------------------------------------------------------------------
# Resolution
# ---------------------------------------------------------------------------


def test_ref_l_claims_its_filenames():
    assert I.resolve_by_name("/d/REFL_1_2_3_partial.txt").name == "REF_L"
    assert I.resolve_by_name("/d/REFL_1_combined_data_auto.txt").name == "REF_L"


def test_unknown_file_falls_back_to_generic():
    inst = I.resolve_by_name("/d/mystery.xyz")
    assert inst.name == "generic"
    assert inst.file_role("/d/mystery.xyz") == UNKNOWN
    assert inst.group_key("/d/mystery.xyz") is None
    assert inst.header_metadata("/d/mystery.xyz") == I.DEFAULT_HEADER_METADATA


def test_resolve_by_name_never_reads_the_file(tmp_path):
    """A REF_L header must not make resolve_by_name claim a foreign name."""
    p = tmp_path / "foreign.xyz"
    p.write_text("# TwoTheta(deg)\n# 1.0\n0.01 1.0 0.1\n")
    assert I.resolve_by_name(str(p)).name == "generic"


def test_resolve_falls_back_to_a_header_sniff(tmp_path):
    """The theta heuristic used to run on every file regardless of name; a
    header sniff is what preserves that for an oddly-named REF_L file."""
    p = tmp_path / "oddly-named.dat"
    p.write_text("# Some preamble\n# TwoTheta(deg) other\n# 0.6 1\n0.01 1.0 0.1\n")
    assert I.resolve(str(p)).name == "REF_L"
    assert I.header_metadata(str(p))["theta"] == pytest.approx(0.3)


def test_resolve_on_a_missing_file_is_generic_not_an_error():
    assert I.resolve("/nonexistent/nope.dat").name == "generic"


# ---------------------------------------------------------------------------
# Nuisance-parameter gate, asked of the instrument rather than the filename
# ---------------------------------------------------------------------------


def test_only_partials_support_nuisance_parameters():
    ref_l = I.REFLInstrument()
    assert ref_l.role_supports_nuisance(PARTIAL) is True
    assert ref_l.role_supports_nuisance(COMBINED) is False
    assert ref_l.role_supports_nuisance(UNKNOWN) is False


def test_generic_refuses_nuisance_parameters():
    assert I.generic().role_supports_nuisance(UNKNOWN) is False
    assert I.generic().role_supports_nuisance(PARTIAL) is False


# ---------------------------------------------------------------------------
# Extensibility — the point of the exercise
# ---------------------------------------------------------------------------


class _FakeInstrument:
    """A third-party instrument, registered the way a plugin would."""

    name = "FAKE"

    def matches(self, file_path, header=""):
        return os.path.basename(file_path).startswith("fake_")

    def file_role(self, file_path):
        return PARTIAL

    def group_key(self, file_path):
        return os.path.basename(file_path).split("_")[1]

    def header_metadata(self, file_path):
        return {
            "dq_is_fwhm": False,
            "num_segments": 3,
            "theta": 1.25,
            "instrument": self.name,
        }

    def role_supports_nuisance(self, role):
        return True


@pytest.fixture
def fake_registered():
    I.register(_FakeInstrument(), first=True)
    yield
    from aure.instruments import registry

    registry._REGISTRY = [i for i in registry._REGISTRY if i.name != "FAKE"]


def test_a_registered_instrument_claims_its_files(fake_registered):
    assert I.resolve_by_name("/d/fake_77_a.dat").name == "FAKE"
    assert I.file_role("/d/fake_77_a.dat") == PARTIAL
    assert I.group_key("/d/fake_77_a.dat") == "77"
    assert I.header_metadata("/d/fake_77_a.dat")["theta"] == 1.25


def test_registering_does_not_disturb_ref_l(fake_registered):
    assert I.resolve_by_name("/d/REFL_1_2_3_partial.txt").name == "REF_L"


def test_a_custom_instrument_drives_the_state_classifier(fake_registered):
    ds = [{"file": "/d/fake_77_a.dat"}, {"file": "/d/fake_77_b.dat"}]
    assert _detect_kind("s", ds) == "partials"


def test_a_custom_instrument_can_reject_mixed_groups(fake_registered):
    ds = [{"file": "/d/fake_77_a.dat"}, {"file": "/d/fake_88_b.dat"}]
    with pytest.raises(ConfigError, match="set_id"):
        _detect_kind("s", ds)


def test_re_registering_a_name_replaces_it():
    from aure.instruments import registry

    before = [i.name for i in I.registered()]
    I.register(_FakeInstrument())
    I.register(_FakeInstrument())
    names = [i.name for i in I.registered()]
    assert names.count("FAKE") == 1
    registry._REGISTRY = [i for i in registry._REGISTRY if i.name != "FAKE"]
    assert [i.name for i in I.registered()] == before


# ---------------------------------------------------------------------------
# Env override
# ---------------------------------------------------------------------------


def test_env_override_forces_an_instrument(monkeypatch, fake_registered):
    monkeypatch.setenv(_ENV_OVERRIDE, "FAKE")
    assert I.resolve_by_name("/d/REFL_1_2_3_partial.txt").name == "FAKE"


def test_env_override_accepts_generic(monkeypatch):
    monkeypatch.setenv(_ENV_OVERRIDE, "generic")
    assert I.resolve_by_name("/d/REFL_1_2_3_partial.txt").name == "generic"


def test_unknown_env_override_is_ignored(monkeypatch):
    monkeypatch.setenv(_ENV_OVERRIDE, "NOPE")
    assert I.resolve_by_name("/d/REFL_1_2_3_partial.txt").name == "REF_L"


# ---------------------------------------------------------------------------
# Phase 3: the previously silent unrecognised-file branch
# ---------------------------------------------------------------------------


def _state_yaml(tmp_path, filename, extra=""):
    """Write a data file and a one-state config that references it."""
    data = tmp_path / filename
    data.write_text("# header\n0.01 1.0 0.1 0.001\n0.02 0.5 0.05 0.001\n")
    cfg = tmp_path / "cfg.yaml"
    cfg.write_text(
        "states:\n"
        f"  - name: A\n"
        f"    data_files: [{filename}]\n" + (f"    {extra}\n" if extra else "")
    )
    return cfg


def test_unrecognised_file_is_warned_about_not_silent(tmp_path, caplog):
    from aure.config import load_user_config

    cfg = _state_yaml(tmp_path, "mystery.xyz")
    with caplog.at_level("WARNING"):
        load_user_config(cfg)
    assert any(
        "no registered instrument recognises" in r.message.lower()
        for r in caplog.records
    ), caplog.text


def test_recognised_file_produces_no_such_warning(tmp_path, caplog):
    from aure.config import load_user_config

    cfg = _state_yaml(tmp_path, "REFL_1_combined_data_auto.txt")
    with caplog.at_level("WARNING"):
        load_user_config(cfg)
    assert not any(
        "no registered instrument recognises" in r.message.lower()
        for r in caplog.records
    )


def test_nuisance_on_an_unrecognised_file_explains_why(tmp_path):
    """Previously this said "detected kind: combined", which described the
    symptom. It must now name the instrument gap and how to close it."""
    from aure.config import load_user_config

    cfg = _state_yaml(tmp_path, "mystery.xyz", extra="theta_offset: true")
    with pytest.raises(ConfigError) as exc:
        load_user_config(cfg)
    msg = str(exc.value)
    assert "partials" in msg  # the historical wording callers match on
    assert "no registered instrument recognises" in msg.lower()
    assert "docs/instruments.md" in msg
    assert _ENV_OVERRIDE in msg


def test_nuisance_still_allowed_on_a_ref_l_partial(tmp_path):
    from aure.config import load_user_config

    cfg = _state_yaml(
        tmp_path, "REFL_1_2_3_partial.txt", extra="theta_offset: true"
    )
    parsed = load_user_config(cfg)
    assert parsed["states"][0]["theta_offset"]["min"] == -0.02


def test_nuisance_still_rejected_on_a_ref_l_combined_file(tmp_path):
    from aure.config import load_user_config

    cfg = _state_yaml(
        tmp_path, "REFL_1_combined_data_auto.txt", extra="theta_offset: true"
    )
    with pytest.raises(ConfigError, match="partials"):
        load_user_config(cfg)


def test_state_records_which_instrument_claimed_it(tmp_path):
    from aure.config import load_user_config

    cfg = _state_yaml(tmp_path, "REFL_1_combined_data_auto.txt")
    assert load_user_config(cfg)["states"][0]["_instrument"] == "REF_L"


def test_state_records_generic_for_an_unclaimed_file(tmp_path):
    from aure.config import load_user_config

    cfg = _state_yaml(tmp_path, "mystery.xyz")
    assert load_user_config(cfg)["states"][0]["_instrument"] == "generic"


def test_instrument_marker_is_stripped_on_setup_dump(tmp_path):
    """``_instrument`` is private state, not part of the setup schema."""
    from aure.setup import dump_setup, load_setup

    data = tmp_path / "REFL_1_combined_data_auto.txt"
    data.write_text("# h\n0.01 1.0 0.1 0.001\n")
    src = tmp_path / "s.yaml"
    src.write_text(
        "sample_description: x\n"
        "states:\n"
        "  - name: A\n"
        f"    data_files: [{data.name}]\n"
    )
    import yaml

    # Assert on structure, not substring: tmp_path itself can contain the word.
    dumped = yaml.safe_load(dump_setup(load_setup(src)))
    for state in dumped["states"]:
        assert not [k for k in state if k.startswith("_")], state


def test_a_custom_instrument_can_permit_nuisance_on_its_own_files(
    tmp_path, fake_registered
):
    """The gate asks the instrument, so a format whose files are all
    single-angle can accept theta_offset even though REF_L would not."""
    from aure.config import load_user_config

    cfg = _state_yaml(tmp_path, "fake_12_a.dat", extra="theta_offset: true")
    parsed = load_user_config(cfg)
    assert parsed["states"][0]["_instrument"] == "FAKE"
    assert parsed["states"][0]["theta_offset"]["max"] == 0.02
